# Generated by Django 5.2.8 on 2025-11-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_device_id_alter_attendance_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='nfc_uid',
            field=models.CharField(blank=True, help_text='NFC card UID for teacher identification', max_length=100, null=True, unique=True),
        ),
    ]
