# Generated by Django 5.2.8 on 2025-11-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_teacherprofile_nfc_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FineRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('threshold_percent', models.PositiveSmallIntegerField(default=75, help_text='If attendance < this percent, fine applies')),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=50.0, help_text='Amount charged per absent day', max_digits=8)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
